### ISSUE TITLE
art-r-translation_find_error

### ISSUE THREAD

**Issue by ActuaryChan** [cosname/art-r-translation#1]
page 45：
最下面代码第三行which里面的语句；
page 63：
最下面的代码中wmins下面的注释中的2xn中的x应该是乘号。
page 172: 第六行，choose（x，y）后面应该把n，k改为x，y
Ps：我只看了前六章，期末完了再看剩下的。

**Comment by taiyun** [comment]
森神威武~

**Comment by yanping** [comment]
好的 我确认以后加进去 @ActuaryChan
