### ISSUE TITLE
中文版本page29的关于seq的错误

### ISSUE THREAD

**Issue by pyloque** [cosname/art-r-translation#2]
在x为单个数值的向量时seq(x) != 1:length(x)
seq(c(10) == 1,2,3,4,5,6,7,8,9,10
1:length(c(10) == 1

**Comment by yixuan** [comment]
谢谢指出，这里确实是原作者考虑不周，更稳健的办法是使用`seq_along(x)`。我会在勘误表里加上这一点。

**Comment by ifduyue** [comment]
第二次印刷仍然引入了一个typo，见 #3
