### ISSUE TITLE
typo on page 29

### ISSUE THREAD

**Issue by ifduyue** [cosname/art-r-translation#3]
`可以看到，如果x非空，seq(x)与seq-along(x)的结果相同`
中的`seq-along(x)`应该为`seq_along(x)`

**Comment by yc3356** [comment]
请问第一章中提到的  ExamsQuiz.txt文件可以在哪里下载到？

**Comment by yixuan** [comment]
@ChrisChen0429 之前联系过原作者，应该是他弄丢了……

**Comment by MasterTinder** [comment]
按照readme里面的说法grade.txt 是用在1.5以及5.1.2中的，也就是书中的ExamsQuiz.txt...但是显然内容不一样，这会对初学者带来很多困扰...
